### ISSUE TITLE
Add a release tag for docopts 0.6.1+fix

### ISSUE THREAD

**Issue by CristianCantoro** [docopt/docopts#10]
I would like to package `docopts` in [Homebrew](https://github.com/Homebrew) and [Linunxbrew](https://github.com/Linuxbrew), but I need a tagged release for it to be inserted in the [core formulae](https://github.com/Homebrew/homebrew-core).

This version is available since 3 years and the [new version of the API](https://github.com/docopt/docopts/issues/5) seems standing still, and even in that casae we can simply have a new release.

EDIT: for the moment I will make a formula for the [devel-only formulae](https://github.com/Homebrew/homebrew-devel-only).

**Comment by Sylvain303** [comment]
No one posted on my shell API proposal, the PR has never be accepted nor discussed… I don't use it for now, but you're welcome to discuss about that. 

Bash is slow when it comes to do a lot of parsing so it uses python version internally, it may be the point this version didn't come popular, mixing python and bash I don't know.

I may propose a new API. I don't know [Linuxbrew](https://github.com/Linuxbrew), I will look at it.

We could write some proposal on the wiki on this project.

**Comment by Sylvain303** [comment]
Done: https://github.com/docopt/docopts/releases

Tell me if you need more.

**Comment by CristianCantoro** [comment]
Thank you. I welcome the new go version and I think it is better that we wait for a new stable release of the new version instead of packaging `docopts` using the last version.
