### ISSUE TITLE
Pre-built Go binaries

### ISSUE THREAD

**Issue by denisidoro** [docopt/docopts#12]
I'm currently trying to use https://github.com/Sylvain303/docopts and I'd like to know if someone can provide pre-built binaries for OSX and ARM
Thanks

**Comment by Sylvain303** [comment]
Hi @denisidoro 

Do you have  OSX ARM hardware available?
Is it 2 binaries OSX and ARM?
or is it an OSX running on ARM CPU?

Would you like 32bits or 64bits binary?

**Comment by Sylvain303** [comment]
@denisidoro is seems quite easy to build with go :-)

With branch: https://github.com/Sylvain303/docopts/tree/docopts-go

Not tested.

Expiration : 2018-07-11 
docopts-OSX
https://framadrop.org/r/GrgZEEYQGZ#+jFWDDNoVmcTaLaYVZUWdnMFMSQp9a+ckIMWq3f5RlU=

docopts-arm
https://framadrop.org/r/MolQK-Liet#SBRxCEmyDEjg0V0hgFsqkkfV1degNgtIgCAjssv1CMg=

copy and rename the file as you need.

Given a working go environment, it seems cross-compiling is trivial:

OSX:
```
env GOOS=darwin GOARCH=386 go build -o docopts-OSX docopts.go
```

arm:

```
env GOOS=linux GOARCH=arm go build -o docopts-arm docopts.go
```

built with:
```
go version
go version go1.10.1 linux/amd64
```

Tell me if it works.
Regards.

**Comment by denisidoro** [comment]
Thank you for the quick response! 
Could you also compile for Android ARM?
I intend to use it with [Termux](https://play.google.com/store/apps/details?id=com.termux)

I tried compiling it with 
```
env GOOS=android GOARCH=arm go build docopts.go
```

but it failed because `/usr/local/opt/go/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1`

I tried with [gomobile](https://godoc.org/golang.org/x/mobile/cmd/gomobile) as well but couldn't find out the correct command.

Also, it would be nice to add this command to some package managers! (apt, homebrew, etc)
Do you plan to do so?

**Comment by Sylvain303** [comment]
nope. As it, the compilation fail:

```
$ env GOOS=android GOARCH=arm go build -o docopts-android docopts.go
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
gcc: error: unrecognized command line option ‘-marm’; did you mean ‘-mabm’?
```
Don't hesitate to ask for help toward your local mobile developer, Linux User Group, or what ever skilled people you may reach easily. 

I will ask on my side.

About packaging…
It would probably come. I will do the debian package when the soft will be ready.

I will attach some pre-built version with each release at first. Now I can add OSX and arm like a charm.
I added a [`Makefile`](https://github.com/Sylvain303/docopts/blob/docopts-go/Makefile) to build all 4 versions.

**Comment by denisidoro** [comment]
Maybe this can help: https://github.com/junegunn/fzf/commit/28ffb9638d7a06b4bfcb87ce6af28c66c2210de3

**Comment by Sylvain303** [comment]
@denisidoro  Thanks! Pretty interesting, I will look at it how I can apply it to build `docopts` release.

Did you try to hack this Dockerfile?

**Comment by Sylvain303** [comment]
I did not test the cross-compile to android yet.
@denisidoro did you try something like: http://rafalgolarz.com/blog/2017/01/15/running_golang_on_android/
I've no android, I can't test it.

**Comment by Sylvain303** [comment]
OK I tried: https://github.com/karalabe/xgo

```
$ xgo github.com/Sylvain303/docopts
Checking docker installation...
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

Checking for required docker image karalabe/xgo-latest... found.
Cross compiling github.com/Sylvain303/docopts...
Fetching main repository github.com/Sylvain303/docopts...
github.com/Sylvain303/docopts (download)
github.com/docopt/docopt-go (download)
...
```

attached as a text file. 

use this command to decode:

```
base64 -d docopts-android-16-arm.base64.txt > docopts-android-16-arm
```
[docopts-android-16-arm.base64.txt](https://github.com/docopt/docopts/files/2114788/docopts-android-16-arm.base64.txt)

Not tested.

**Comment by denisidoro** [comment]
Sorry for reviving this thread after so much time, but could you please reupload the binaries? I'm afraid I lost them :/

**Comment by denisidoro** [comment]
Nevermind: https://github.com/denisidoro/docopts/releases/tag/v0.6.3-alpha1

**Comment by Sylvain303** [comment]
Hi @denisidoro ,

Yes, far far away from the past. :wink: 

I added a new issue in the meantime: #32

OSX binaries are easy to produce, arm for android I did not test it, as written in this issue above.

You may contribute, by describing the process to test and build binaries for arm-android.

I can test and build for OSX via travis, or crosscompile from GNU/Linux. 

It seems possible to [build for android on travis](https://docs.travis-ci.com/user/languages/android/ ), but I haven't any knowledge on that platform yet.

Thanks for your interest.
Regards.
