### ISSUE TITLE
docopts.sh: line 14: type: write error: Broken pipe

### ISSUE THREAD

**Issue by CristianCantoro** [docopt/docopts#16]
When running tests with the latest build of `docopts-go`:
```
./language_agnostic_tester.py ./testee.sh
```

I get results like this:
```
================================= 6: BAD JSON =================================
result> ./docopts.sh: line 14: type: write error: Broken pipe
{"--all": false}

expect> {"--all": false}
```

The full log is attached here: [test.log](https://github.com/docopt/docopts/files/2133429/test.log), I have seen that running the command multuple times the tests who fail are different. Sometimes I have that all tests pass.

My bash version is `GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)`.

**Comment by Sylvain303** [comment]
It seems related to the `readlink` binary selector for OSX.

https://github.com/docopt/docopts/blob/master/docopts.sh#L14

Could you try to have a working code on your platform?

What is your output for:

```
type -p greadlink readlink
type -p greadlink
type -p readlink
type type
```
the line 14 codes should return the fullpath of `greadlink` if both are installed.

For example on my computer I can have:

```
type -p gawk awk
/usr/bin/gawk
/usr/bin/awk
```

**Comment by CristianCantoro** [comment]
What should happen if `greadlink` is not installed? 

I noticed that the problem could be related to the factg that `linuxbrew` has its own versions of `greadlink` and `readlink` and after disabling it I could use the system  `greadlink` and  `readlink`.

With linuxbrew activated:
```bash
$ type -p greadlink readlink
greadlink is /home/cristian/.linuxbrew/bin/greadlink
readlink is /home/cristian/.linuxbrew/bin/readlink
```

without it (system):
```bash
$ type -p greadlink readlink
greadlink not found
readlink is /bin/readlink
```

I also notice that in Linuxbrew `readlink` is a symbolic link to `greadlink`:
```bash
$ realpath $(which greadlink)                                           
/home/cristian/.linuxbrew/Cellar/coreutils/8.29/bin/greadlink
$ realpath $(which readlink) 
/home/cristian/.linuxbrew/Cellar/coreutils/8.29/bin/greadlink
```
and:
```bash
$ /home/cristian/.linuxbrew/bin/greadlink  --version         
readlink (GNU coreutils) 8.29
...
```

while for the system version:
```bash
$ /bin/readlink --version         
readlink (GNU coreutils) 8.25
...
```

I get the error quite at random, I could run the tests several times without failure, I don't know why I am seeing this behavior, and it happens only when I use the linuxbrew-installed `greadlink`/`readlink`.

**Comment by CristianCantoro** [comment]
@Sylvain303:
>If greadlink is not installed, the onliner on line 14 should print the **path** of readlink (2nd choice) and head -1 should suffice to return the path. Your output shows greadlink not found which not empty, nor a valid path. :(
>
> `type` here returns different kind of answer.

Ok, the problem was that I normally use zsh` as my shell, but the script is executed with bash. if I run the following from bash and with `linuxbrew` disabled:

```
$ type -p greadlink readlink
/bin/readlink
$ type -p greadlink
$ type -p readlink
/bin/readlink
$ type type
type is a shell builtin
```

**Comment by Sylvain303** [comment]
commit https://github.com/docopt/docopts/commit/89e001c5111a2625da9fea77158f30950d7c426f should fix this issue too.
