### ISSUE TITLE
Readme should reflect that this is for shell, not golang

### ISSUE THREAD

**Issue by riordan** [docopt/docopts#21]
The program's highly usable if you're already familiar with docopts from another context, but the core readme documentation for some reason reflects that this is for GOLANG.

**Comment by Sylvain303** [comment]
Hi @riordan 

The top of the [README.md](https://github.com/docopt/docopts/blob/master/README.md) says:

> docopt for shell

More specifically, this tools is oriented for [GNU/bash](https://www.gnu.org/software/bash/).

The original version of `docopts` was still for bash but written in python. The `S` at the end stand for `shell`.

The golang is just a support for having pre-built binaries especially for legacy GNU/Linux system where python is not available or not an option. Golang static binaries are particularly useful for just dropping the binary in the `PATH`.

Could you provide an introduction of the `README.md` that would better suite the goal I mentioned above?

Or I may wrongly understood your request.

Regards,
Sylvain.

**Comment by Sylvain303** [comment]
@riordan 

I did merge the doc in 

https://github.com/docopt/docopts/commit/402965151d5d155e92c894236b8b0bf6295f24d7

It should me more explicit.

Hope that answer your request.
Thanks.
