### ISSUE TITLE
Document that bash 3.2 on macOS won't work

### ISSUE THREAD

**Issue by rdonkin** [docopt/docopts#24]
I built and tried docopts on macOS, and found that the examples don't work - apparently because bash 4.x is required due to use of associative arrays.

If this is correct, would like to add something to `README.md` near the top saying that macOS is not supported due to bash 3.2, unless you [upgrade bash to 4.x](https://apple.stackexchange.com/a/292760) using Homebrew, and adjust shebang lines in scripts.  (Apple won't upgrade to 4.x due to its policy on GPLv3.)

Example of errors, had this with several examples:
```
$ ./naval_fate.sh 
panic: "usage:" (case-insensitive) not found.

goroutine 1 [running]:
main.main()
	/Users/richard/gocode/src/github.com/docopt/docopts/docopts.go:423 +0xd87
../docopts.sh: line 127: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
../docopts.sh: line 128: typeset: -A: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
docopt_print_ARGS => ARGS
```

**Comment by Sylvain303** [comment]
hi @rdonkin 

Yes, you're right. You need to upgrade to bash 4 for associative arrays.

Thanks GPLv3 for identifying  non-Libre Software. ;-)

However, `docopts` supports non associative array mode with `-G` or without `-A`
The behavior permit execution on legacy system too.

```bash
cd docopts/examples
source ../docopts.sh
help=$(docopt_get_help_string cat-n_wrapper_example.sh )
docopts -G args -h "$help" -V "3.0" : --count=3 filename_here
```
outputs

```
args_count='3'
args_FILE=('filename_here')
```

or without `-G` nor `-A` you also have the behavior mentioned in the [old doc](https://github.com/docopt/docopts/blob/master/old_README.rst)

```bash
docopts -h "$help" -V "3.0" : --count=3 filename_here
```

outputs: (without prefix, evaled it may collide with other variable in bash)

```
count='3'
FILE=('filename_here')
```

I hope it may help you.

There's example without `-A` and without using the helper [here](https://github.com/docopt/docopts/blob/master/examples/without_docopts_sh_lib/rock_no-stdin_example.sh).

I will document what you suggest about bash 3.2 on macOS. Its also valid on legacy GNU/Linux version.
I will also merge old documentation in a single README.

Thanks.

**Comment by rdonkin** [comment]
Thanks for the tips.  I tried your first 2 examples in a script on bash 3.2 and they gave errors in the helper:

```
# Exclude brew packages from PATH
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/bin:/Users/richard/gocode/bin bash -x mac-test1.sh
+ cd ../docopts-repo/examples
+ source ../docopts.sh
++++ type -p greadlink readlink
++++ head -1
+++ /usr/bin/readlink -f ../docopts.sh
/usr/bin/readlink: illegal option -- f
usage: readlink [-n] [file ...]
++ docopt_sh_me=
+++ dirname ''
++ docopt_sh_dir=.
++ [[ '' == \-\-\a\u\t\o ]]
++ docopt_get_help_string cat-n_wrapper_example.sh
++ local myfname=cat-n_wrapper_example.sh
++ sed -n -e '/^# Usage:/,/^$/ s/^# \?//p'
+ help=
+ docopts -G args -h '' -V 3.0 : --count=3 filename_here
panic: "usage:" (case-insensitive) not found.

goroutine 1 [running]:
main.main()
	/Users/richard/gocode/src/github.com/docopt/docopts/docopts.go:423 +0xd87
```
Without the PATH setting, I do have `greadlink` installed via brew `coreutils`, and there's no readlink error but the same panic error about finding 'usage:'.

Problem seems to be that `readlink` on macOS doesn't have the `-f` option to canonicalize symlinks. 

Not sure why it's required to canonicalize - if you don't need that and can use full path to script that may include symlinks, you could use this code instead, which works fine on bash 3.2.57(1) / macOS 11 (even without GNU readlink via brew), and also on bash 4.4.19(1) / Ubuntu 18.04:

```
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" 2>/dev/null)" && pwd 2>/dev/null)"
SCRIPT_PATH=$DIR/$(basename $0)
```
This works when script is run via `./script` or `bash script`.

[This gist](https://gist.github.com/rdonkin/05915bd86475389a94953997f80db9ff) includes some other options that canonicalize symlinks without requiring GNU readlink.  Re-tested on bash 3.2.

The last example using `examples/without_docopts_sh_lib/rock_no-stdin_example.sh` and no helper did work.

The issues above are quite minor and only in the `docopts.sh` helper, so it would be good to support bash 3.2 on Mac.  Use cases include Macs that are locked-down or where installing a new version of bash and fixing shebang lines is too much overhead.

**Comment by rdonkin** [comment]
I have made a start on changes to `docopts.sh` to support bash 3.2 and Mac when -G is used - not sure if I'm missing some changes as I'm new to docopt.

[Shellcheck](https://github.com/koalaman/shellcheck) informs me that the `docopt_sh_me` and `docopt_sh_dir` vars are unused.

Have done a little testing with your commands above in -G mode, and it seems most scripts will work apart from when they are using bash 4.x features
```
diff --git a/docopts.sh b/docopts.sh
index 97d5c96..fa698e2 100644
--- a/docopts.sh
+++ b/docopts.sh
@@ -11,8 +11,14 @@
 # docopt_auto_parse() modify $HELP and $ARGS
 
 # compute this file dirpath:
-docopt_sh_me=$($(type -p greadlink readlink | head -1 ) -f "${BASH_SOURCE[0]}")
-docopt_sh_dir="$(dirname "$docopt_sh_me")"
+# docopt_sh_me=$($(type -p greadlink readlink | head -1 ) -f "${BASH_SOURCE[0]}")
+# docopt_sh_dir="$(dirname "$docopt_sh_me")"
+
+# Detect macOS
+sed_options=''
+if [[ "$(uname -s)" == 'Darwin' ]]; then
+    sed_options='-E'    # Enable sane regexes for sed on macOS - see re_format(1)
+fi
 
 # fetch Usage: from the given filename
 # usually $0 in the main level script
@@ -28,7 +34,7 @@ docopt_get_help_string() {
     # /^# Usage:/,/^$/ : filter range blocks from '# Usage:' to empty line
     #  s/^# \?// : substitute comment marker and an optional space
     #  p : print
-    sed -n -e '/^# Usage:/,/^$/ s/^# \?//p' < $myfname
+    sed $sed_options -n -e '/^# Usage:/,/^$/ s/^# ?//p' < $myfname
 }
 
 # fetch version information from the given filename or string
@@ -38,7 +44,7 @@ docopt_get_version_string() {
     if [[ -f "$1" ]] ; then
         # filter the block (all blocks) starting at a "# Usage:" and ending
         # at an empty line, one level of comment markup is removed
-        sed -n -e '/^# ----/,/^$/ s/^# \?//p' < "$1"
+        sed $sed_options -n -e '/^# ----/,/^$/ s/^# \?//p' < "$1"
     else
         # use docopts --separator behavior
         echo "$1"
@@ -125,7 +131,7 @@ docopt_print_ARGS() {
     # inspired by:
     # https://stackoverflow.com/questions/6660010/bash-how-to-assign-an-associative-array-to-another-variable-name-e-g-rename-t#8881121
     declare -A myassoc
-    eval $(typeset -A -p $assoc|sed "s/ $assoc=/ myassoc=/")
+    eval $(typeset -A -p $assoc|sed $sed_options "s/ $assoc=/ myassoc=/")
 
     # loop on keys
```

**Comment by Sylvain303** [comment]
Hi @rdonkin 

Thanks a lot for your Mac OS contribution. For the diff you may use a Pull Request (PR) to suggest the change. I will look at it in another reply. I also mention #16 which is also related to macOS `readlink`.

So answering the ticket subject, I commited a modified version of the documentation and add some minor fix of the behavior related to mangled argument.

https://github.com/docopt/docopts/commit/402965151d5d155e92c894236b8b0bf6295f24d7

Hope that helps.

I will next try to fix `readlink` related issue and examine you fix.

**Comment by rdonkin** [comment]
I will do a couple of PRs - one on README, fixing typos and grammar, and one for macOS.

I made some sed changes above, it turns out that GNU sed 4.2 was the first version where `-E` was supported, so my fix would break some older Linuxes with GNU sed 4.1 or below.  However, 4.2 was released in 2009, so maybe it's OK to break 10 year old old sed versions?

If you want to support older GNU sed versions, I will adjust one of the sed commands to use [POSIX compatible regexes](https://unix.stackexchange.com/a/125669), which work on both BSD/macOS and GNU sed.  There are only 3 sed commands in `docopts.sh` and two of them don't need changes anyway.  This avoids complex version detection and should work with any `sed`.

On `readlink`, it seems that the `docopt_sh_me` and `docopt_sh_dir` vars are not used anywhere, so I would hope those lines can be commented out or deleted.

**Comment by rdonkin** [comment]
Since the bats tests won't run on bash 3.2, I didn't realise that in fact the var `docopt_sh_me` is used in the Git submodule repo for bats tests.

This var seems to only be used in a couple of tests, and in both cases I believe that canonicalisation of any symlinks should not matter, as the tests are just testing this var for an empty or non-empty value

I've updated PR #27 to compute the absolute path to script, giving an equivalent of `readlink -f` with just `pwd` and `cd`, as long as symlinks don't matter.

The bats tests now pass on bash 4.4 / Ubuntu 18.04, and the `examples/legacy_bash` scripts also work on bash 3.2 / macOS.

**Comment by Sylvain303** [comment]
Hi @rdonkin ,                                                                                                                                   
  
So I merged your PR.

I looked at the `readlink` issue, and decided to remove it from `docopts.sh`. As the fix was quite heavy for a really poor usage, and only for macOS. This should also fixes #14.

I also changed all shebangs to `#!/usr/bin/env bash`

I also restored and completed [examples/legacy_bash/sshdiff_legacy.sh](https://github.com/docopt/docopts/blob/master/examples/legacy_bash/sshdiff_legacy.sh) with the rewrite I was thinking about.

I also developped the `-G` for globals in `doctops.sh`

```bash
source docopts.sh --auto -G "$@"
# the debug helper also support it
docopt_print_ARGS -G
```

So I restored `docopt_print_ARGS -G` calls in legacy scripts.

Examples in:
* [examples/legacy_bash/sshdiff_with_docopts.sh](https://github.com/docopt/docopts/blob/master/examples/legacy_bash/sshdiff_with_docopts.sh)
* [build_doc.sh](https://github.com/docopt/docopts/blob/master/build_doc.sh#L150)

I also corrected the embedded documentation in `docopts.sh` about associative array and bash3.2 legacy support.

I think we can close this issue, about bash3.2 support in `docopts`.
Which works when using globals with `-G` or not using `-A`.

**Comment by Cato2** [comment]
Hi @Sylvain303 - you've been busy, lots of improvements and the `--auto -G` feature looks good!

Fine to close this, bash 3.2 now works fine.

I will do a separate PR that allows use with `set -u` (error on undefined variable), which is quite popular as part of the ["bash unofficial strict mode"](http://redsymbol.net/articles/unofficial-bash-strict-mode/) to catch coding mistakes.

**Comment by rdonkin** [comment]
Hi @Sylvain303 - you've been busy, lots of improvements and the --auto -G feature looks good!

Fine to close this, bash 3.2 now works fine.

I will do a separate PR that allows use with set -u (error on undefined variable), which is quite popular as part of the "bash unofficial strict mode" to catch coding mistakes.
