### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by ghost** [docopt/docopts#5]
I started docopts a year and a half ago in order to better maintain the many shell scripts I wrote for work, but for a long time now I haven't worked there nor with shell scripts at all, so my interest has been waning. As such, I'm going to retire as docopts maintainer.

Maintainership isn't really anything formal in the docopt organization, of course, since all members can commit in any subproject anyway, but I've also got solo admin access to docopts's PyPI page, which is something I should probably turn over to someone else if I'm going away. If no volunteers step up immediately, I suppose @halst would be okay?

**Comment by Sylvain303** [comment]
So someone is maintaining or not?

**Comment by keleshev** [comment]
@Sylvain303 no, not at the moment.

**Comment by Sylvain303** [comment]
Ok, I can probably do it. I will step deeper in the code to see what is needed. I modified the python wrapper localy, to encapsulate docopts call in a shell function, and solve assoc array scoping (declare -A). I have a bunch of script in many languages and will docopt them all.

**Comment by Sylvain303** [comment]
the develop branch proposes a very different API, quite odd to me. Do you know why this API (in the man page) is so far from the python docopt API? Is it possible to add a wiki on this project so we can describe the API wanted? I think a library form of API that matches python version could be quite simple to handle. 

Something like the following code snipet, to be completed…
Specifying the associative array $name and some shell centric behavior have to be considered, too.

~~~bash
#!/bin/bash
source docopts.sh

parsed=$(docopt -A args "$help_string" "$@" "$version" "$options_first")
eval "$parsed"
~~~

and may be some shell helpers too:

~~~bash
get_help_string $0
~~~

**Comment by keleshev** [comment]
I think it's best to create an issue to talk over API changes. I don't write shell scripts, so I can't comment on this. Anyone from @docopt team could give feedback on this?

**Comment by Sylvain303** [comment]
I think we need both: wiki and issue. Wiki can also be faked by an file API_proposal.md on a branch though.

**Comment by keleshev** [comment]
Wiki is now enabled for this project.

**Comment by Sylvain303** [comment]
OK, thanks. I will migrate the API proposal to the wiki and propose a roadmap. When the branch I forked will be stable enough and the doc updated, I will send a pull request. The new version is totally backward compatible. I did not follow the code in the develop branch.

**Comment by Sylvain303** [comment]
@keleshev what is needed to become maintainer of docotps shell (Bash) version ?

**Comment by matt2000** [comment]
So, a year later, is anyone still interested in this? It'd be nice to get a definitive answer on whether this project will see further development, and if so, whether it will be backward compatible.

**Comment by Sylvain303** [comment]
@matt2000 Thanks asking. I'm still interested. 

But I think, after using much more bash scripts, that having docopts based on using python doctopt as a subcommand is not the way bash scripts is evolving in real environment. See #9 and #7 (needs to be updated) As bash scripts tend to be short, if not stand alone, and mostly are not installed as part of a package but copied to their destination. Specially on production server, for example.

As I work more and more on legacy code. I think #9 should be strongly encouraged. We should discuss it in its own issue though.

**Comment by matt2000** [comment]
I don't care about removing the Python dependency; I understand the value of it, but it is not important for my personal usage, since Python is always available to me. I'd just like to see (1) The removal of the warnings about changing API in the README, (2) #7 or something like it get merged, and (3) The develop branch officially removed to avoid confusing potential contributors about the direction of future development. If those things were done, I think more people could use, and maybe contribute, to this project. If later someone can reimplement the parser in BASH, that's great, but this project need not be in limbo until then.

So, @keleshev / @docopt, What needs to happen to make @Sylvain303 the maintainer so that this project can be revived?

**Comment by matt2000** [comment]
@keleshev @docopt ping?

**Comment by Sylvain303** [comment]
@matt2000 I published an issue in the main repository for becoming a new maintainer:

https://github.com/docopt/docopt/issues/417

My new `docopts` version is a binary written in golang available [here](https://github.com/Sylvain303/docopts/tree/docopts-go). No api change from the 0.6.2 python version.

So it will also fix #9 :-)

**Comment by mboersma** [comment]
@Sylvain303 all the docopt* projects are still under the chief maintainership of @keleshev. I know he hasn't been responsive for a long time, but I don't think there is a consensus among the other maintainers on how to proceed. We also don't have permission to add people to the main "docopt" group (although we can add collaborators apparently).

But it's pretty painful to see this project (and other docopt implementations) wither. I'll start a conversation among the maintainer group and see if we can get some agreement on how to proceed.

**Comment by Sylvain303** [comment]
Thanks @mboersma.

I'm the new maintainer, let's start with #13. ;)
